In [484]:
import requests
from bs4 import BeautifulSoup

In [485]:
cate = 'economic'  # politics, society
url = 'https://news.daum.net/{}#1'.format(cate)
url

'https://news.daum.net/economic#1'

In [486]:
res = requests.get(url)

In [487]:
path = 'body > div.container-doc.cont-category > main > section > div.main-sub > div.box_g.box_news_major > ul > li'

soup = BeautifulSoup(res.text)
lis = soup.select(path)

In [488]:
news_urls = []
for li in lis:
    news_url = li.select('a')[0]['href']
    news_urls.append(news_url)
news_urls

['https://v.daum.net/v/20220406163156193',
 'https://v.daum.net/v/20220406163101148',
 'https://v.daum.net/v/20220406163017115',
 'https://v.daum.net/v/20220406162715954',
 'https://v.daum.net/v/20220406162615892',
 'https://v.daum.net/v/20220406162422812',
 'https://v.daum.net/v/20220406162338779',
 'https://v.daum.net/v/20220406161154303',
 'https://v.daum.net/v/20220406162042668',
 'https://v.daum.net/v/20220406161604469']

In [489]:
news_urls[0]

'https://v.daum.net/v/20220406163156193'

In [490]:
res1 = requests.get(news_urls[0])

In [491]:
soup1 = BeautifulSoup(res1.text, 'html.parser')

In [492]:
news_texts = []

path1 = '#harmonyContainer > section > p'

for p in soup1.select(path1):
    news_texts.append(p.text)

In [493]:
cate_news_list = []

for cate in ['economic', 'culture', 'digital']:
    
    cate_news_texts = []
    url = 'https://news.daum.net/{}#1'.format(cate)

    res = requests.get(url)

    path = 'body > div.container-doc.cont-category > main > section > div.main-sub > div.box_g.box_news_major > ul > li'


    soup = BeautifulSoup(res.text)
    lis = soup.select(path)

    news_urls = []
    for li in lis:
        news_url = li.select('a')[0]['href']
        print(news_url)
        news_urls.append(news_url)


    # print(news_urls)

    for url in news_urls:
        news_texts = []
        res1 = requests.get(url)

        soup1 = BeautifulSoup(res1.text, 'html.parser')

        path1 = '#harmonyContainer > section > p'

        text = ''
        for p in soup1.select(path1):
            text += p.text

        news_texts.append(text)

        cate_news_texts.append(news_texts)
    
    cate_news_list.append(cate_news_texts)

https://v.daum.net/v/20220406163156193
https://v.daum.net/v/20220406163101148
https://v.daum.net/v/20220406163017115
https://v.daum.net/v/20220406162715954
https://v.daum.net/v/20220406162615892
https://v.daum.net/v/20220406162422812
https://v.daum.net/v/20220406162338779
https://v.daum.net/v/20220406161154303
https://v.daum.net/v/20220406162042668
https://v.daum.net/v/20220406161604469
https://v.daum.net/v/20220406140100583
https://v.daum.net/v/20220406120142922
https://v.daum.net/v/20220406115905727
https://v.daum.net/v/20220406114930421
https://v.daum.net/v/20220406113232646
https://v.daum.net/v/20220406113128598
https://v.daum.net/v/20220406110618288
https://v.daum.net/v/20220406105356514
https://v.daum.net/v/20220406101424512
https://v.daum.net/v/20220406101325477
https://v.daum.net/v/20220406153014714
https://v.daum.net/v/20220406151507109
https://v.daum.net/v/20220406151405044
https://v.daum.net/v/20220406145822271
https://v.daum.net/v/20220406150027396
https://v.daum.net/v/2022

In [494]:
len(cate_news_list)

3

In [495]:
len(cate_news_list[2])

10

In [496]:
economic_news = cate_news_list[0]
politics_news = cate_news_list[1]
society_news = cate_news_list[2]

In [497]:
total_news = economic_news + politics_news + society_news

In [498]:
len(total_news)

30

In [499]:
category = ['eco']*10 + ['pol']*10 + ['soc']*10
news = total_news

news_df = pd.DataFrame({'cate':category, 'news':total_news})
news_df

cate                                               news
0   eco  [기사내용 요약 김대지 청장, 판교테크노밸리 입주기업과 간담회 "맞춤형 지원 방안 ...
1   eco  [오랜만의 아이폰SE지만, 매번 보아온 아이폰SE와 같기도 하다. 이번 애플의 3세...
2   eco  [[편집자주] 국내에 인터넷전문은행이 설립된 지 꼭 5년이다. '기대반 우려반'으로...
3   eco  [ [이데일리 최정훈 기자] 최저임금의 급격한 인상 이후 사업주의 인건비를 지원하기...
4   eco  [“윤석열 정부는 복지공약과 감세공약 중 어느 하나는 폐기할 수밖에 없을 것이다.”...
5   eco  [(부산=연합뉴스) 조정호 기자 = 자본시장의 안정적인 결제를 책임지는 한국거래소 ...
6   eco  ["정치인이 1순위, 관료 2순위, 교수가 최악."다음달 10일 출범할 윤석열 정부...
7   eco  [정부와 한국수력원자력이 고리 원자력 발전 2호기 계속운전을 밀어붙이며 문재인 정부...
8   eco  [6일 투자은행(IB) 업계에 따르면, 회생절차를 진행 중인 쌍용차는 우선협상대상자...
9   eco  [(서울=뉴스1) 황두현 기자 = 리오프닝(경제활동 재개) 수혜 업종으로 꼽힌 화장...
10  pol  ['만병의 근원'이라고 불리는 스트레스. 현대 사회에선 학교, 가족, 직장, 병원 ...
11  pol  [큐레이터 출신인 김성은 백남준아트센터 관장은 백남준과 인연이 각별하다. 공부를 마...
12  pol  [기사내용 요약 여행업 손실보상·관광업 규제완화·한시적 세제혜택 요청 인수위 "정책...
13  pol  [(서울=뉴스1) 윤슬빈 여행전문기자 = 코로나19 장기화로 해외여행의 대체여행지로...
14  pol  [ 윤석열 대통령 당선인 부인 김건희 여사의 공개활동 본격화 시점에 관심이 쏠리는 ...
15  pol  [[헤럴드경제=육성연 기자]특별할 것 같은 ‘슈퍼푸드(super food)’ 용어가...
16  pol  [티라노사우루스 렉스는 지상 최대 육식공룡의 하나로 몸길이 14m에 1.5m 길이의...
17  pol  [오랜 경험을 쌓은 베테랑 연출의 손과 발로 일하는 것은 많은 걸 배우는 기회이기도...
18  pol                  [본 기사는 월간산 2022년 4월호에 수록된 기사입니다.]
19  pol                  [본 기사는 월간산 2022년 4월호에 수록된 기사입니다.]
20  soc  [메신저리보핵산(mRNA) 기반의 신종 코로나바이러스 감염증(COVID-19·코로나...
21  soc  [“노무 규정은 국가마다 크게 다릅니다. 폴란드는 근로자 건강검진이 필수고, 이집트...
22  soc  [모토로라의 한국 스마트폰 시장 복귀가 초읽기에 들어갔다. 중저가 시장 진입을 목표...
23  soc  [(서울=뉴스1) 오현주 기자 = 신종 코로나바이러스 감염증(코로나19) 확진자 안...
24  soc                                                 []
25  soc  [(지디넷코리아=김양균 기자)고려대의대 학부생들이 네이버 검색어를 분석해 우리나라 ...
26  soc  [ 카카오가 올 연말까지 계열사 30~40곳을 정리하기로 했다. 골목상권 침해 논란...
27  soc  [(지디넷코리아=이정현 미디어연구소)미국 우주 발사체 기업 로켓랩이 이번 달 야심 ...
28  soc  [국내게임사가 도전하고 있는 블록체인 게임시장에서 '인플레이션' 방지 대책 중요성이...
29  soc  [최근 출시되는 많은 자동차들은 앞차와 간격 조정, 차선이탈방지 등 기능은 기본적으...

In [500]:
news_df.iloc[7, 1]

['정부와 한국수력원자력이 고리 원자력 발전 2호기 계속운전을 밀어붙이며 문재인 정부의 ‘탈원전 정책 뒤집기’를 시도하고 있다. 배경에는 계속운전에 대한 자체 경제성 평가가 수명 연장에 유리하게 결론난 것이 작용하고 있다. 월성 1호기 조기 폐쇄를 위해 경제성 평가를 조작했다는 의혹을 받은 만큼, 계속운전이 적합하다는 경제성 평가 결과를 무시하기 어려웠던 것으로 분석된다. 설비 보강 비용, 주민 지원금 같은 유지 비용을 뺀 순이익도 상당할 것으로 예측됐다. 익명을 요구한 에너지 전문가는 “고리 2호기는 원자로 헤드 교체 등 굵직한 안전성 보강을 이미 해왔기 때문에 다른 원전과 달리 설비 개선을 위한 큰 비용이 들지 않는다”면서 “원전을 돌리는데 들어가는 비용을 다 빼고도 6~7년 정도 가동한다고 하면 약 1000억원 대의 순이익이 날 것”이라고 했다. 특히 고리 2호기 경제성 평가에는 월성 1호기 경제성 조작 의혹 사건 이후 한수원이 마련한 새 평가지침을 처음 적용했다. 감사원은 2020년 10월 ‘월성 1호기 감사결과 처분요구 통보’에서 원전 계속운전 여부 판단을 위한 객관적인 경제성 평가 지침을 개발하라고 한수원에 요구했다. 이에 한수원은 지난해 자체 개발한 지침을 바탕으로 고리 2호기 경제성 평가를 진행했다. 특히 월성 1호기 경제성 조작 문제로 관련 공무원들이 재판까지 받는 상황이다 보니 청와대 등 ‘윗선’의 개입 없이 객관적 평가를 할 환경이 의도치 않게 마련됐다. 정범진 경희대 원자력공학과 교수는 “과거에는 평가 지침이 명확히 없어 평가 결과도 정부 입김에 따라 고무줄처럼 조절했다”면서 “월성 1호기 사태로 이런 부분이 문제 되자 평가 환경이 좀 더 객관적으로 변한 것”이라고 설명했다. 한수원이 4일 제출한 주기적 안전평가서는 원안위를 거쳐 원자력안전기술위원회에서 18개월 이내 심사해야 한다. 이후 이를 바탕으로 원안위에서 다시 24개월 안에 연장 여부를 결정한다. 연장 허가 후에도 설비 개선 등에도 1~2년가량이 더 필요하기 때문에 실제 가동까지는

In [501]:
import re

In [502]:
def preprocessing(text):
    text = re.sub('[^가-힣ㄱ-ㅎ ]', ' ', text[0])
    return text

In [503]:
news_df['news1'] = news_df['news'].apply(lambda x : preprocessing(x))

In [504]:
news_df

cate                                               news  \
0   eco  [기사내용 요약 김대지 청장, 판교테크노밸리 입주기업과 간담회 "맞춤형 지원 방안 ...   
1   eco  [오랜만의 아이폰SE지만, 매번 보아온 아이폰SE와 같기도 하다. 이번 애플의 3세...   
2   eco  [[편집자주] 국내에 인터넷전문은행이 설립된 지 꼭 5년이다. '기대반 우려반'으로...   
3   eco  [ [이데일리 최정훈 기자] 최저임금의 급격한 인상 이후 사업주의 인건비를 지원하기...   
4   eco  [“윤석열 정부는 복지공약과 감세공약 중 어느 하나는 폐기할 수밖에 없을 것이다.”...   
5   eco  [(부산=연합뉴스) 조정호 기자 = 자본시장의 안정적인 결제를 책임지는 한국거래소 ...   
6   eco  ["정치인이 1순위, 관료 2순위, 교수가 최악."다음달 10일 출범할 윤석열 정부...   
7   eco  [정부와 한국수력원자력이 고리 원자력 발전 2호기 계속운전을 밀어붙이며 문재인 정부...   
8   eco  [6일 투자은행(IB) 업계에 따르면, 회생절차를 진행 중인 쌍용차는 우선협상대상자...   
9   eco  [(서울=뉴스1) 황두현 기자 = 리오프닝(경제활동 재개) 수혜 업종으로 꼽힌 화장...   
10  pol  ['만병의 근원'이라고 불리는 스트레스. 현대 사회에선 학교, 가족, 직장, 병원 ...   
11  pol  [큐레이터 출신인 김성은 백남준아트센터 관장은 백남준과 인연이 각별하다. 공부를 마...   
12  pol  [기사내용 요약 여행업 손실보상·관광업 규제완화·한시적 세제혜택 요청 인수위 "정책...   
13  pol  [(서울=뉴스1) 윤슬빈 여행전문기자 = 코로나19 장기화로 해외여행의 대체여행지로...   
14  pol  [ 윤석열 대통령 당선인 부인 김건희 여사의 공개활동 본격화 시점에 관심이 쏠리는 ...   
15  pol  [[헤럴드경제=육성연 기자]특별할 것 같은 ‘슈퍼푸드(super food)’ 용어가...   
16  pol  [티라노사우루스 렉스는 지상 최대 육식공룡의 하나로 몸길이 14m에 1.5m 길이의...   
17  pol  [오랜 경험을 쌓은 베테랑 연출의 손과 발로 일하는 것은 많은 걸 배우는 기회이기도...   
18  pol                  [본 기사는 월간산 2022년 4월호에 수록된 기사입니다.]   
19  pol                  [본 기사는 월간산 2022년 4월호에 수록된 기사입니다.]   
20  soc  [메신저리보핵산(mRNA) 기반의 신종 코로나바이러스 감염증(COVID-19·코로나...   
21  soc  [“노무 규정은 국가마다 크게 다릅니다. 폴란드는 근로자 건강검진이 필수고, 이집트...   
22  soc  [모토로라의 한국 스마트폰 시장 복귀가 초읽기에 들어갔다. 중저가 시장 진입을 목표...   
23  soc  [(서울=뉴스1) 오현주 기자 = 신종 코로나바이러스 감염증(코로나19) 확진자 안...   
24  soc                                                 []   
25  soc  [(지디넷코리아=김양균 기자)고려대의대 학부생들이 네이버 검색어를 분석해 우리나라 ...   
26  soc  [ 카카오가 올 연말까지 계열사 30~40곳을 정리하기로 했다. 골목상권 침해 논란...   
27  soc  [(지디넷코리아=이정현 미디어연구소)미국 우주 발사체 기업 로켓랩이 이번 달 야심 ...   
28  soc  [국내게임사가 도전하고 있는 블록체인 게임시장에서 '인플레이션' 방지 대책 중요성이...   
29  soc  [최근 출시되는 많은 자동차들은 앞차와 간격 조정, 차선이탈방지 등 기능은 기본적으...   

                                                news1  
0   기사내용 요약 김대지 청장  판교테크노밸리 입주기업과 간담회  맞춤형 지원 방안 마...  
1   오랜만의 아이폰  지만  매번 보아온 아이폰  와 같기도 하다  이번 애플의  세대...  
2    편집자주  국내에 인터넷전문은행이 설립된 지 꼭  년이다   기대반 우려반 으로 ...  
3     이데일리 최정훈 기자  최저임금의 급격한 인상 이후 사업주의 인건비를 지원하기 ...  
4    윤석열 정부는 복지공약과 감세공약 중 어느 하나는 폐기할 수밖에 없을 것이다   ...  
5    부산 연합뉴스  조정호 기자   자본시장의 안정적인 결제를 책임지는 한국거래소 청...  
6    정치인이  순위  관료  순위  교수가 최악  다음달   일 출범할 윤석열 정부의...  
7   정부와 한국수력원자력이 고리 원자력 발전  호기 계속운전을 밀어붙이며 문재인 정부의...  
8    일 투자은행     업계에 따르면  회생절차를 진행 중인 쌍용차는 우선협상대상자였...  
9    서울 뉴스   황두현 기자   리오프닝 경제활동 재개  수혜 업종으로 꼽힌 화장품...  
10   만병의 근원 이라고 불리는 스트레스  현대 사회에선 학교  가족  직장  병원 등...  
11  큐레이터 출신인 김성은 백남준아트센터 관장은 백남준과 인연이 각별하다  공부를 마치...  
12  기사내용 요약 여행업 손실보상 관광업 규제완화 한시적 세제혜택 요청 인수위  정책 ...  
13   서울 뉴스   윤슬빈 여행전문기자   코로나   장기화로 해외여행의 대체여행지로 ...  
14   윤석열 대통령 당선인 부인 김건희 여사의 공개활동 본격화 시점에 관심이 쏠리는 가...  
15   헤럴드경제 육성연 기자 특별할 것 같은  슈퍼푸드              용어가 ...  
16  티라노사우루스 렉스는 지상 최대 육식공룡의 하나로 몸길이    에      길이의 ...  
17  오랜 경험을 쌓은 베테랑 연출의 손과 발로 일하는 것은 많은 걸 배우는 기회이기도 ...  
18                    본 기사는 월간산     년  월호에 수록된 기사입니다   
19                    본 기사는 월간산     년  월호에 수록된 기사입니다   
20  메신저리보핵산       기반의 신종 코로나바이러스 감염증          코로나 ...  
21   노무 규정은 국가마다 크게 다릅니다  폴란드는 근로자 건강검진이 필수고  이집트는...  
22  모토로라의 한국 스마트폰 시장 복귀가 초읽기에 들어갔다  중저가 시장 진입을 목표로...  
23   서울 뉴스   오현주 기자   신종 코로나바이러스 감염증 코로나    확진자 안내...  
24                                                     
25   지디넷코리아 김양균 기자 고려대의대 학부생들이 네이버 검색어를 분석해 우리나라 사...  
26   카카오가 올 연말까지 계열사      곳을 정리하기로 했다  골목상권 침해 논란을...  
27   지디넷코리아 이정현 미디어연구소 미국 우주 발사체 기업 로켓랩이 이번 달 야심 찬...  
28  국내게임사가 도전하고 있는 블록체인 게임시장에서  인플레이션  방지 대책 중요성이 ...  
29  최근 출시되는 많은 자동차들은 앞차와 간격 조정  차선이탈방지 등 기능은 기본적으로...

In [505]:
stw = pd.read_csv('./data_files/stopwords-ko.txt', header=None)
stopwords = list(stw.iloc[:, 0].values)
stopwords

def remove_stopwords(doc):
    text = [w for w in doc.split() if w not in stopwords]
    return ' '.join(text)

In [506]:
news_df['news2'] = news_df.news1.apply(remove_stopwords)

In [507]:
news_df.to_csv('news_df.csv')

In [508]:
from konlpy.tag import Hannanum, Komoran, Kkma
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.cluster import AgglomerativeClustering, KMeans, DBSCAN

In [509]:
kor = Komoran()

In [510]:
news_df.loc[15, 'news']

['[헤럴드경제=육성연 기자]특별할 것 같은 ‘슈퍼푸드(super food)’ 용어가 이제는 여기저기에서 등장한다. 애초에 슈퍼푸드가 가졌던 명성이 줄어드는 듯한 분위기다.이는 슈퍼푸드를 구분짓는 공식 기준이 따로 없기 때문이다. 슈퍼푸드란 영양이 풍부해 건강에 도움을 주는 식품을 말한다. 영양소로는 항산화물질이 단골로 등장한다. 주로 식물성 식품에서 슈퍼푸드가 언급되는 이유는 이 때문이다. 항산화물질은 식물이 가진 영양소 ‘파이토케미컬(phytochemical)에 다량 들어있다.통곡물로는 귀리가 해당 목록에서 모두 등장한다. 최근 오트밀크(Oat Milk, 귀리우유)의 글로벌 인기도 각종 매체와 기관에서 귀리를 슈퍼푸드로 언급한 영향도 있다. 귀리는 베타글루칸(수용성 식이섬유 일종) 영양소를 자랑할 만 하다. 캐나다 토론토 대학 연구결과에 따르면 귀리 속 베타글루칸은 ‘나쁜’ LDL 콜레스테롤 수치를 낮추는 데 도움이 된다.채소 중에서는 푸른 잎채소의 영원한 경쟁자인 케일과 시금치가 우선적으로 언급된다. 케일은 세계보건기구(WHO)가 극찬한 ‘최고의 채소’이며, 미국 경제전문 매체 ‘월스트리트 치트시트’가 농무부 자료로 평가한 채소 1위 등의 수상경력이 화려하다. 항암 성분이 풍부하며, 각종 비타민과 미네랄 함유량도 다른 채소보다 많다. 시금치 역시 케일만큼 뛰어난 효능을 인정받은 슈퍼푸드다. 세계암연구재단은 최고의 항암식품으로 시금치를 선정했다.생선으로는 연어가 꼽힌다. 테레사 펑 미국 하버드 공중보건대학 영양학과 교수는 하버드 블로그를 통해 자신이 매일 먹기 위해 노력하는 식품중 하나로 연어를 소개한 바 있다. 연어는 특히 최근 몇 년간 가장 관심이 높아진 영양소 두 개를 다량 가지고 있다. 바로 오메가 3지방산과 비타민D이다.과일에서는 베리류가 공통적으로 언급된다. 베리류는 영양학자들이 가장 많이 손꼽는 슈퍼푸드 과일이다. 여성에게 좋은 과일로 알려져 있으며, 항산화물질이 우수한 과일로도 유명하다. 블루베리는 일찌감치 슈퍼푸드 대명사로 불려졌으며, 항산

In [511]:
docs = []

for n in news_df['news2']:
    docs.append(kor.nouns(n))

In [512]:
docs

[['기사',
  '내용',
  '요약',
  '김',
  '대지',
  '청장',
  '판교테크노밸리',
  '입주',
  '기업',
  '간담회',
  '맞춤',
  '지원',
  '방안',
  '마련',
  '기업',
  '성장',
  '환경',
  '조성',
  '세종',
  '뉴시스',
  '종택',
  '기자',
  '김',
  '대지',
  '국세청장',
  '성장',
  '동력',
  '중심',
  '첨단',
  '중소',
  '벤처기업',
  '세무조사',
  '부담',
  '완화',
  '맞춤',
  '정지원',
  '방안',
  '마련',
  '김',
  '대지',
  '청장',
  '이날',
  '경기',
  '성남시',
  '경기',
  '창조경제',
  '혁신',
  '센터',
  '판교테크노밸리',
  '입주',
  '중소',
  '벤처기업',
  '대표',
  '등',
  '현장',
  '소통',
  '간담회',
  '말',
  '이날',
  '간담회',
  '우리나라',
  '성장',
  '동력',
  '산업',
  '중심',
  '중소',
  '벤처기업',
  '등',
  '무상',
  '어려움',
  '파악',
  '맞춤',
  '정지원',
  '방안',
  '마련',
  '판교테크노밸리',
  '여개',
  '기업',
  '입주',
  '여명',
  '근무',
  '중',
  '연간',
  '매출',
  '총액',
  '조원',
  '규모',
  '우리나라',
  '성장',
  '동력',
  '산업',
  '중추',
  '역할',
  '담당',
  '김',
  '청장',
  '코로나',
  '유행',
  '러시아',
  '우크라이나',
  '전쟁',
  '발발',
  '등',
  '대외',
  '여건',
  '정부',
  '재원',
  '안정',
  '조달',
  '중소기업',
  '대표',
  '감사',
  '김',
  '청장',
  '코로나',
  '어려움',
  '피해',
  '중소기업',
  '등',
  '정지원',


In [513]:
for i in range(len(docs)):
    docs[i] = ' '.join(docs[i])

In [514]:
docs

['기사 내용 요약 김 대지 청장 판교테크노밸리 입주 기업 간담회 맞춤 지원 방안 마련 기업 성장 환경 조성 세종 뉴시스 종택 기자 김 대지 국세청장 성장 동력 중심 첨단 중소 벤처기업 세무조사 부담 완화 맞춤 정지원 방안 마련 김 대지 청장 이날 경기 성남시 경기 창조경제 혁신 센터 판교테크노밸리 입주 중소 벤처기업 대표 등 현장 소통 간담회 말 이날 간담회 우리나라 성장 동력 산업 중심 중소 벤처기업 등 무상 어려움 파악 맞춤 정지원 방안 마련 판교테크노밸리 여개 기업 입주 여명 근무 중 연간 매출 총액 조원 규모 우리나라 성장 동력 산업 중추 역할 담당 김 청장 코로나 유행 러시아 우크라이나 전쟁 발발 등 대외 여건 정부 재원 안정 조달 중소기업 대표 감사 김 청장 코로나 어려움 피해 중소기업 등 정지원 전국 세무서 중심 정지원 추진단 운영 납부 기한 연장 환급 금 조기 지급 등 적극 실시 경영 자금 유동성 지원 노력 설명 국세청 올해 연구 인력 개발비 세액 공제 사전 심사 제도 편리 이용 수 제출 서류 중소기업 세액 공제 감면 제도 상담 진행 계획 간담회 참석 기업 대표 성장 산업 활성 정지원 대책 마련 중소기업 세무조사 축소 유예 확대 연구 인력 개발비 세액 공제 여부 불확실성 해소 방안 등 건의 김 청장 경제 활성 고용 창출 지원 스타트 업 한국판 뉴딜 일자리 창출 중소기업 등 정기 세무조사 선정 제외 대상 확대 기업 성장 수 환경 조성 노력 약속 납세자 소통 납세자 공감 체감 수 효과 지원 방안 마련 공감 언론 뉴시스',
 '오랜만 아이폰 아이폰 애플 세대 아이폰 기존 구형 아이폰 디자인 계승 두뇌 아이폰 강점 인치 손 콤팩트 한 크기 만원 대 가격 아이폰 탑재 파워 풀 최신 바이오 닉 칩 아이폰 처음 입문 고객 콤팩트 한 디자인 고객 맞춤 세대 아이폰 고객 니즈 성능 업그레이드 기존 아이폰 플래그 시리즈 얼굴 인식 페이스 탑재 홈 버튼 지문 로그인 기존 아이폰 공식 아이폰 메인 화면 처음 아이폰 때 것 점 바이오 닉 성능 이다 코어 머신 러닝 기

In [515]:
# vec = CountVectorizer()
vec = CountVectorizer(max_df=0.7, min_df=2)

x = vec.fit_transform(docs)
x

<30x612 sparse matrix of type '<class 'numpy.int64'>'
	with 1950 stored elements in Compressed Sparse Row format>

In [516]:
news_arr = x.toarray()
news_arr

array([[0, 0, 0, ..., 1, 0, 0],
       [3, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [517]:
x.shape

(30, 612)

In [518]:
km = KMeans(n_clusters=3)
dbs = DBSCAN(eps=50, min_samples=5)
agg = AgglomerativeClustering(n_clusters=3, linkage='ward')

In [519]:
km.fit_predict(news_arr)

array([1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [520]:
dbs.fit_predict(news_arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [521]:
agg.fit_predict(news_arr)

array([0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [522]:
# n_gram
# original => "뉴스 슬기 로우 라디오 생활 방송 일시"
# 2_gram => 뉴스 슬기 로우 라디오 생활 방송 일시 (뉴스 슬기) (슬기 로우) (로우 라디오) ...

In [523]:
# vec = TfidfVectorizer()
vec = TfidfVectorizer(max_df=0.7, min_df=2, ngram_range=(1, 2))

x = vec.fit_transform(docs)
x.toarray()

array([[0.        , 0.        , 0.        , ..., 0.05502146, 0.        ,
        0.        ],
       [0.19066047, 0.        , 0.        , ..., 0.        , 0.        ,
        0.06355349],
       [0.        , 0.        , 0.        , ..., 0.        , 0.03667221,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [524]:
km = KMeans(n_clusters=3)
dbs = DBSCAN(eps=50, min_samples=5)
agg = AgglomerativeClustering(n_clusters=3, linkage='ward')

In [525]:
km.fit_predict(news_arr)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [526]:
dbs.fit_predict(news_arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [527]:
agg.fit_predict(news_arr)

array([0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)